In [461]:
from bs4 import BeautifulSoup as bs
import matplotlib.pyplot as plt
import requests
import re
import pandas as pd

In [462]:
url = "https://groww.in/recurring-deposit/rd-interest-rates"
req = requests.get(url)
soup = bs(req.content, "html.parser")

In [463]:
for table in soup.find_all('table',{"dir":"ltr"}):
    table_data = table

In [464]:
rows = []
for row in table_data.find_all('tr'):
    rows.append(row)

In [465]:
bank_names = []
min_rate = []
max_rate = []

In [466]:
for row in rows[1:]:
    data = []
    for row_data in row.find_all('td'):
        data.append(row_data)
    # print(data)
    bank_names.append(re.sub('[^A-Za-z\s+]','',data[0].text))
    min_rate.append(float(re.sub('[^0-9.\s+]','',data[1].text.split()[0])))
    max_rate.append(float(re.sub('[^0-9.\s+]','',data[1].text.split()[-1])))

In [467]:
df = pd.DataFrame({"index":bank_names,"Bank name":bank_names,"Min rate":min_rate,"Max rate":max_rate})
df.sort_values(by='Min rate',inplace=True,ascending=False)
df.set_index('index',inplace=True)
df

                                                 Bank name  Min rate  Max rate
index
IDBI Bank                                        IDBI Bank      7.00      7.15
IDFC First Bank                            IDFC First Bank      6.75      7.25
Equitas Small Finance Bank      Equitas Small Finance Bank      6.25      6.50
Indian Bank                                    Indian Bank      6.25      6.30
Post Office RD Interest Rate  Post Office RD Interest Rate      6.20      6.20
IndusInd Bank                                IndusInd Bank      5.50      6.00
Jana Small Finance Bank            Jana Small Finance Bank      5.50      6.75
ESAF Small Finance Bank            ESAF Small Finance Bank      5.00      6.00
Yes Bank                                          Yes Bank      5.00      6.50
Indian Overseas Bank                  Indian Overseas Bank      4.90      5.20
Ujjivan Small Finance Bank      Ujjivan Small Finance Bank      4.75      6.50
UCO Bank                                          UCO Bank      4.70      5.00
RBL Bank                                          RBL Bank      4.50      6.30
Bandhan Bank                                  Bandhan Bank      4.50      5.00
Punjab and Sind Bank                  Punjab and Sind Bank      4.45      5.25
Canara Bank                                    Canara Bank      4.45      5.25
SBI RD Interest Rates                SBI RD Interest Rates      4.40      5.50
Union Bank of India                    Union Bank of India      4.40      5.60
PNB                                                    PNB      4.40      5.30
Axis Bank RD Interest Rates    Axis Bank RD Interest Rates      4.40      5.75
HDFC RD Interest Rates              HDFC RD Interest Rates      4.40      5.50
BOB RD Interest Rates                BOB RD Interest Rates      4.30      5.25
Kotak Bank RD Interest Rates  Kotak Bank RD Interest Rates      4.30      5.20
Bank of India                                Bank of India      4.30      5.05
Central Bank of India                Central Bank of India      4.20      5.00
South Indian Bank                        South Indian Bank      4.10      5.65
Bank of Maharashtra                    Bank of Maharashtra      4.00      4.90
AU Small Finance Bank                AU Small Finance Bank      4.00      6.00
Karur Vysya Bank                          Karur Vysya Bank      4.00      5.35
ICICI RD Interest Rates            ICICI RD Interest Rates      3.50      5.50
Citibank                                          Citibank      2.75      3.00
Lakshmi Vilas Bank                      Lakshmi Vilas Bank      2.75      6.00

In [468]:
def getMaturity(bank,principle, timeInYears):
    rate = df.loc[bank,'Min rate']
    n = 4
    ans = 0
    progress = [principle]
    for i in range(1,(timeInYears*12)+1):
        ans = ans + (principle * pow((1 + (rate/(n*100))), n*(i/12)))
        progress.append(round(ans,2))
    return progress[-1]

In [469]:
getMaturity('IDBI Bank',2000,10)

347403.47